# Generated by Django 6.0.4 on 2026-08-29 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': (['-recorded_at'],), 'verbose_name': ('Измерение',), 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время замера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurement.sensor', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название датчика'),
        ),
    ]
